CREATE TABLE REGISTRO
(
ID_REG INTEGER,
NOMBRE VARCHAR2(40),
EMAIL VARCHAR2(40),
EDAD INTEGER,
 CONSTRAINT PK_ID_REG PRIMARY KEY (ID_REG));
 
INSERT INTO REGISTRO VALUES (1,'GABRIELA','GAB_28@GMAIL.COM',26); 
INSERT INTO REGISTRO VALUES (2,'NESTOR','NES_08@GMAIL.COM',25);
INSERT INTO REGISTRO VALUES (3,'CEDRIC','CED_18@GMAIL.COM',18);
INSERT INTO REGISTRO VALUES (4,'ALBERTO','ALB_03@GMAIL.COM',16);
INSERT INTO REGISTRO VALUES (5,'KAREN','KAR_17@GMAIL.COM',10);
INSERT INTO REGISTRO VALUES (6,'FELIPE','FEL_17@GMAIL.COM',12);

SELECT * FROM REGISTRO;
SELECT * FROM REGISTRO_MAYORES;
SELECT * FROM REGISTRO_MENORES;

CREATE TABLE REGISTRO_MAYORES
(
ID_REGMAYOR INTEGER,
NOMBRE VARCHAR2(40),
EMAIL VARCHAR2(40),
EDAD INTEGER,
 CONSTRAINT PK_ID_REGMAYOR PRIMARY KEY (ID_REGMAYOR)); 

CREATE TABLE REGISTRO_MENORES
(
ID_REGMENOR INTEGER,
NOMBRE VARCHAR2(40),
EMAIL VARCHAR2(40),
EDAD INTEGER,
 CONSTRAINT PK_ID_REGMENOR PRIMARY KEY (ID_REGMENOR)); 
 
CREATE OR REPLACE TRIGGER RESPALDO_REGISTRO 
AFTER INSERT ON REGISTRO FOR EACH ROW
BEGIN
IF :NEW.EDAD >= 18 THEN

INSERT INTO REGISTRO_MAYORES VALUES (:NEW.ID_REG, :NEW.NOMBRE, :NEW.EMAIL, :NEW.EDAD);

ELSIF :NEW.EDAD <=0 THEN

INSERT INTO REGISTRO_MAYORES VALUES (:NEW.ID_REG, :NEW.NOMBRE, :NEW.EMAIL, :NEW.EDAD);
RAISE_APPLICATION_ERROR (-20001,'LO SIENTO NO SE ACEPTA LA EDAD INGRESADA');

ELSE

INSERT INTO REGISTRO_MENORES VALUES (:NEW.ID_REG, :NEW.NOMBRE, :NEW.EMAIL, :NEW.EDAD);

END IF;
END;
/


