--EJERCICIO1:

CREATE TABLE XXX
( 
ID_XXX INTEGER,
EDAD INTEGER);

CREATE OR REPLACE TRIGGER XXX_MAYOR_EDAD BEFORE INSERT ON XXX FOR EACH ROW
BEGIN
IF :NEW.EDAD < 18 THEN
RAISE_APPLICATION_ERROR (-20001,'LO SIENTO CHAMACO PRECOZ');
END IF;
END;
/
INSERT INTO XXX VALUES (1,26);
SELECT * FROM XXX;

--EJERCICIOS2:

CREATE TABLE NOMINA_XXX
( 
ID_NOMINAXXX INTEGER,
LOGIN VARCHAR2(10),
SALDO INTEGER);

CREATE OR REPLACE TRIGGER ACTUALIZAR_SALDO BEFORE UPDATE ON NOMINA_XXX FOR EACH ROW
BEGIN
:NEW.SALDO:=:NEW.SALDO+:OLD.SALDO;
END;
/
INSERT INTO NOMINA_XXX VALUES (3,'GAB',20000);
SELECT * FROM NOMINA_XXX;

UPDATE NOMINA_XXX SET
SALDO=40000 WHERE ID_NOMINAXXX=3;
SELECT * FROM NOMINA_XXX;
