
--CREAREMOS UNA TABLA SIMPLE PARA PROBAR EL PODER DE SQL

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);

--PRENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR

SET SERVEROUTPUT ON;

--VAMOS A EMPEZAR CON UN BLOQUE PL SQL

DECLARE

--AQUI SE DECLARAN LAS VARIABLES A USARSE

EDAD INTEGER;
YEARS INTEGER;
BEGIN

--AQUI VA LA LOGICA DEL PROGRAMA
YEARS:=26;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES '||EDAD);

END;
/
