--CREAREMOS UNA TABLA SIMPLE PARA PROBAR EL PODER DE SQL

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);
--PRENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR

SET SERVEROUTPUT ON;

--VAMOS A EMPEZAR CON UN BLOQUE PL SQL

DECLARE

--AQUI SE DECLARAN LAS VARIABLES A USARSE

EDAD INTEGER;
YEARS INTEGER;
BEGIN

--AQUI VA LA LOGICA DEL PROGRAMA
YEARS:=26;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES '||EDAD);

END;
/

--CREAR UN BLOQUE PL SQL QUE GENERE 20000 REGISTROS DE SECUENCIA EN LA TABLE DANCE
 BEGIN
 
  FOR I IN 1..200000 LOOP
    INSERT INTO DANCE VALUES(I,'GABY',26);
    
    END LOOP;
    END;
    /
    
    -- HACEMOS UN SELECT PARA VER QUE HACE
    
     SELECT * FROM DANCE;
      
  -- SISTEMA DE PELICULAS
  
  CREATE TABLE PELICULA (ID_PRLICULA INTEGER,
                        TITULO VARCHAR2(120), 
                        SINOPSIS VARCHAR2(500),
                        CLASIFICACION VARCHAR2(5),
                        CONSTRAINT PK_ID_PELICULA PRIMARY KEY(ID_PELICULA)
                        );
-- VEMOS LA TABLA
                        DESCRIBE PELICULA;
  CREATE TABLA HORARIO (ID_HORARIO INTEGER,
                        ID_PELICULA INTEGER
                        HORARIO VARCHAR2(8),
                        CONSTRAINT PK_HORARIO PRIMARY KEY(ID_HORARIO),
                        CONSTRAINT FK1_ID_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA)
                        );
                        
   CREATE TABLA SALA (ID_SALA INTEGER,
                        ID_PELICULA INTEGER
                        NUM_SALA INTEGER,
                        CONSTRAINT PK_ID_SALA PRIMARY KEY(ID_SALA),
                        CONSTRAINT FK2_ID_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA)
                        );
