--CREAREMOS UNA TABLA SIMPLE PARA PROBAR EL PODER DE SQL

CREATE TABLE DANCE(ID_DANCE INTEGER, NOMBRE VARCHAR2(40), EDAD INTEGER);
--PRENDEMOS EL SERVIDOR EN MODO DE DESARROLLADOR

SET SERVEROUTPUT ON;

--VAMOS A EMPEZAR CON UN BLOQUE PL SQL

DECLARE

--AQUI SE DECLARAN LAS VARIABLES A USARSE

EDAD INTEGER;
YEARS INTEGER;
BEGIN

--AQUI VA LA LOGICA DEL PROGRAMA
YEARS:=26;
EDAD:=YEARS*365;

DBMS_OUTPUT.PUT_LINE('TU EDAD EN DIAS ES '||EDAD);

END;
/

--CREAR UN BLOQUE PL SQL QUE GENERE 20000 REGISTROS DE SECUENCIA EN LA TABLE DANCE
 BEGIN
 
  FOR I IN 1..200000 LOOP
    INSERT INTO DANCE VALUES(I,'GABY',26);
    
    END LOOP;
    END;
    /
    
    -- HACEMOS UN SELECT PARA VER QUE HACE
    
      SELECT * FROM DANCE;
