 CURSOR CUR_PAISESTUDIANTE IS SELECT NOMBRE, HABITANTE, CARRERA FROM PAISES, ESTUDIANTE WHERE PAISES.ID_PAIS = ESTUDIANTE.ID_PAIS;
   

    BEGIN
   
       FOR FILA IN CUR_PAISESTUDIANTE LOOP
   
        DBMS_OUTPUT.PUT_LINE('NOMBRE DEL PAIS '||FILA.NOMBRE|| 'NUMERO DE HABITANTES  ' || FILA.HABITANTE || 'CARRERA '|| FILA.CARRERA);
         
         END LOOP;
         
 END;

SELECT NOMBRE, HABITANTE, CARRERA FROM PAISES, ESTUDIANTE WHERE PAISES.ID_PAIS = ESTUDIANTE.ID_PAIS;
